#!/bin/bash
echo "Running FarmData2 pre-commit checks..."

# Prevent commits to the production branch
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
if [ "$BRANCH" = "production" ]; then
  echo
  echo "You cannot commit directly to the production branch."
  echo "The production branch should only be updated by merging development into it."
  echo "This operation should only be performed by maintainers."
  echo
  exit 255
fi

if [ "$BRANCH" = "development" ]; then
  echo
  echo "You cannot commit directly to the development branch."
  echo "Instead create a feature branch and commit your changes to it."
  echo "Then push your feature branch to GitHub and create a pull request."
  echo
  exit 255
fi

# Function to check if any staged files have been modified
check_modified_staged_files() {
  local modified_files=$(git diff --name-only --cached)
  for file in $modified_files; do
    if [ -f "$file" ] && ! git diff --quiet "$file"; then
      return 0  # Found a modified staged file
    fi
  done
  return 1  # No modified staged files found
}

# For all other branches, run the pre-commit checks using lint-staged.
if npm run check:staged; then
  # Check if any staged files were modified during the pre-commit checks
  if check_modified_staged_files; then
    echo
    echo "Some staged files were modified during the pre-commit checks."
    read -p "Would you like to stage these changes now? (y/N) " response
    if [[ "$response" =~ ^[Yy] ]]; then
      git add -u
      echo "Changes have been staged. Running pre-commit checks again..."
      if ! npm run check:staged; then
        echo
        echo "FarmData2 pre-commit checks failed after staging new changes."
        echo "The commit will not be made."
        echo "Review the output above for details."
        echo "Fix the issues and try your commit again."
        echo
        exit 255
      fi
    else
      echo "Changes were not staged. Please stage them manually if needed."
    fi
  fi
  echo "Done."
  echo "Making the commit."
  echo
  exit 0
else
  echo
  echo "FarmData2 pre-commit checks failed."
  echo "The commit will not be made."
  echo "Review the output above for details."
  echo "Fix the issues and try your commit again."
  echo
  exit 255
fi
